### ISSUE TITLE
Possible Mistake in SPL Grammar Specification

### ISSUE THREAD

**Issue by ziqin** [CirQ/CS323-Compilers#4]
> - Version: Oct 7th
> - File: `cs323-project1.pdf`
> - Section: Appendix B (Grammar Specification), Expression
>
> ```
> Exp -> Exp ASSIGN Exp
>     | Exp AND Exp
>     | Exp OR Exp
>     | Exp LT Exp
>     | Exp LE Exp
>     | Exp GT Exp
>     | Exp GE Exp
>     | Exp NE Exp
>     | Exp EQ Exp
>     | Exp PLUS Exp
>     | Exp MINUS Exp
>     | Exp MUL Exp
>     | Exp DIV Exp
>     | LP Exp RP
>     | MINUS Exp
>     | NOT Exp
>     | ID LP Args RP
>     | ID LP RP
>     | Exp LB Exp LB 👈
>     | Exp DOT ID
>     | ID
>     | INT
>     | FLOAT
>     | CHAR 
> ```

In the 19th line of the production of `Exp`, `Exp -> Exp LB Exp LB` is specified. Shall we change it into `Exp LB Exp RB`?

**Comment by CirQ** [comment]
You are definitely right. Please send a pull request to fix the file syntax.txt in this repository so that we could record your contribution.
